### ISSUE TITLE
`go get` fails when nanomsg not installed (unclear)

### ISSUE THREAD

**Issue by jbenet** [op/go-nanomsg#14]
```
% go get -u github.com/op/go-nanomsg
# github.com/op/go-nanomsg
../../../op/go-nanomsg/bus.go:5:11: fatal error: 'nanomsg/bus.h' file not found
 #include <nanomsg/bus.h>
          ^
1 error generated.
```

**Comment by op** [comment]
Just to add to this issue, the error message given with go 1.5 seems to be pretty descriptive;

```
Package nanomsg was not found in the pkg-config search path.
Perhaps you should add the directory containing `nanomsg.pc'
to the PKG_CONFIG_PATH environment variable
No package 'nanomsg' found
pkg-config: exit status 1
FAIL    github.com/op/go-nanomsg [build failed]
```

**Comment by aliridha1510** [comment]
Setting top to                           : C:\Users\Ali-Haouari\Desktop\nanomsgxx
Setting out to                           : C:\Users\Ali-Haouari\Desktop\nanomsgxx\build
Checking for 'msvc' (c compiler)         : C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\CL.exe
Checking for 'msvc' (c++ compiler)       : C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\CL.exe
Checking for library nanomsg             : not found
The configuration failed
(complete log in C:\Users\Ali-Haouari\Desktop\nanomsgxx\build\config.log)
