### ISSUE TITLE
Support abstract unix pipes in ipc://

### ISSUE THREAD

**Issue by majek** [op/go-nanomsg#23]
Normal implementations support @ symbol in ipc, for exmaple: "ipc://@/tmp/blah.ipc"

That means abstract unix pipe. go-nanomsg crashes with that. Abstract sockets, the C-way: "ipc://\x00/tmp/blah.ipc" kindof work - but the /tmp/blah.ipc is ignored and it's treated as abstract socket without a name: "@"

**Comment by op** [comment]
What are you trying to do? Unless this is supported by libnanomsg, it. I'd suggest to file this bug against nanomsg. I haven't work with abstract pipes, but it looks like it's Linux only too?

**Comment by gdamore** [comment]
Abstract pipes are indeed Linux specific.

**Comment by op** [comment]
@gdamore Thanks. Do nanomsg support it?

**Comment by gdamore** [comment]
Not explicitly.  I’m not sure what additional effort besides a special path
name would be necessary to make it function more fully than that.

**Comment by gdamore** [comment]
Looking at it, no, these are not supported.  It would be relatively easy to
fix that.

**Comment by op** [comment]
@gdamore Wow, thanks for looking into it! Don't sweat it, closing this issue since there doesn't seem like a big demand for the feature. ;)
