### ISSUE TITLE
use pkg-config nanomsg instead of libnanomsg

### ISSUE THREAD

**Issue by gdamore** [op/go-nanomsg#24]
We are delivering nanomsg 0.9 and later with nanomsg.pc as the file.

**Comment by op** [comment]
Ah, did not know about this. Looks like it requires some other change too. I have not monitored changes to nanomsg for a while. Hope to get some time to add all the changes between 0.8 and 0.9 some day. Thanks!

(If someone feels tempted, feel free to have a look. I'm currently on OS X and have never run this project here. Has errors changed between 0.8 and 0.9 or has it always been broken?)
